apiVersion: v1
kind: PersistentVolume
metadata:
  annotations: {}
  name: codex-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Pi
  csi:
    driver: seaweedfs-csi-driver
    readOnly: false
    volumeAttributes:
      collection: "codex-dsn-prod"
      path: "/services/codex"
      replication: "002"
    volumeHandle: "codex-pv"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: codex-pvc
  namespace: codex-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
  storageClassName: ""
  volumeName: codex-pv
