# Default values for codex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override chart name
nameOverride: ""

# Override chart full name
fullnameOverride: ""

# Replicas
replica:
  # Replicas count
  count: 50

# StatefulSet
statefulSet:
  # First replica index
  ordinalsStart: 1
  # For single replica we will skip replica index in the StatefulSet name
  # and it is useful only when no more than one replica is planned to be deployed
  # otherwise, when replica will be increased > 1, previous StatefulSet will be deleted
  # and new ones with index in the names will be created
  # this is why by default we set it to false, to avoid destructive transition
  #        name     StatefulSet
  # true:  codex --> codex
  # false: codex --> codex-1
  prettify: false

image:
  # Image repository
  repository: codexstorage/nim-codex
  # Image tag
  tag: 0.2.1
  # Image pull policy
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []

# Lifecycle
lifecycle: {}

# Namespace
namespaceOverride: ""

# StatefulSet labels
labels: {}
  # foo: bar

# StatefulSet annotations
annotations: {}
  # foo: bar

# ServiceAccount is required for init-env container to get node External IP
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  rbac:
    # Specifies whether RBAC resources should be created
    create: true
    # rbac specific annotations
    annotations: {}
      # foo: bar
    # rbac specific labels
    labels: {}
      # foo: bar
    # Get node External IP
    clusterRules:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "watch"]
    # Get service NodePort - not use currently
    rules:
      # - apiGroups: [""]
      #   resources: ["services"]
      #   verbs: ["get", "list", "watch"]

# Pod labels
podLabels: {}
  # foo: bar

# Pod annotations
podAnnotations: {}
  # foo: bar

podSecurityContext: {}
  # fsGroup: 1000
  # runAsGroup: 1000
  # runAsUser: 1000
  # runAsNonRoot: true

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Codex container command with arguments
codex:
  command:
  # known as Docker ENTRYPOINT
  # - /bin/bash
  # - /docker-entrypoint.sh
  args:
  - codex
  - persistence
  - prover
  - --bootstrap-node=spr:CiUIAhIhAiJvIcA_ZwPZ9ugVKDbmqwhJZaig5zKyLiuaicRcCGqLEgIDARo8CicAJQgCEiECIm8hwD9nA9n26BUoNuarCEllqKDnMrIuK5qJxFwIaosQ3d6esAYaCwoJBJ_f8zKRAnU6KkYwRAIgM0MvWNJL296kJ9gWvfatfmVvT-A7O2s8Mxp8l9c8EW0CIC-h-H-jBVSgFjg3Eny2u33qF7BDnWFzo7fGfZ7_qc9P
  - --bootstrap-node=spr:CiUIAhIhAyUvcPkKoGE7-gh84RmKIPHJPdsX5Ugm_IHVJgF-Mmu_EgIDARo8CicAJQgCEiEDJS9w-QqgYTv6CHzhGYog8ck92xflSCb8gdUmAX4ya78QoemesAYaCwoJBES39Q2RAnVOKkYwRAIgLi3rouyaZFS_Uilx8k99ySdQCP1tsmLR21tDb9p8LcgCIG30o5YnEooQ1n6tgm9fCT7s53k6XlxyeSkD_uIO9mb3
  - --bootstrap-node=spr:CiUIAhIhA6_j28xa--PvvOUxH10wKEm9feXEKJIK3Z9JQ5xXgSD9EgIDARo8CicAJQgCEiEDr-PbzFr74--85TEfXTAoSb195cQokgrdn0lDnFeBIP0QzOGesAYaCwoJBK6Kf1-RAnVEKkcwRQIhAPUH5nQrqG4OW86JQWphdSdnPA98ErQ0hL9OZH9a4e5kAiBBZmUl9KnhSOiDgU3_hvjXrXZXoMxhGuZ92_rk30sNDA
  - --bootstrap-node=spr:CiUIAhIhA7E4DEMer8nUOIUSaNPA4z6x0n9Xaknd28Cfw9S2-cCeEgIDARo8CicAJQgCEiEDsTgMQx6vydQ4hRJo08DjPrHSf1dqSd3bwJ_D1Lb5wJ4Qt_CesAYaCwoJBEDhWZORAnVYKkYwRAIgFNzhnftocLlVHJl1onuhbSUM7MysXPV6dawHAA0DZNsCIDRVu9gnPTH5UkcRXLtt7MLHCo4-DL-RCMyTcMxYBXL0
  - --bootstrap-node=spr:CiUIAhIhAzZn3JmJab46BNjadVnLNQKbhnN3eYxwqpteKYY32SbOEgIDARo8CicAJQgCEiEDNmfcmYlpvjoE2Np1Wcs1ApuGc3d5jHCqm14phjfZJs4QrvWesAYaCwoJBKpA-TaRAnViKkcwRQIhANuMmZDD2c25xzTbKSirEpkZYoxbq-FU_lpI0K0e4mIVAiBfQX4yR47h1LCnHznXgDs6xx5DLO5q3lUcicqUeaqGeg
  - --bootstrap-node=spr:CiUIAhIhAgybmRwboqDdUJjeZrzh43sn5mp8jt6ENIb08tLn4x01EgIDARo8CicAJQgCEiECDJuZHBuioN1QmN5mvOHjeyfmanyO3oQ0hvTy0ufjHTUQh4ifsAYaCwoJBI_0zSiRAnVsKkcwRQIhAJCb_z0E3RsnQrEePdJzMSQrmn_ooHv6mbw1DOh5IbVNAiBbBJrWR8eBV6ftzMd6ofa5khNA2h88OBhMqHCIzSjCeA
  - --bootstrap-node=spr:CiUIAhIhAntGLadpfuBCD9XXfiN_43-V3L5VWgFCXxg4a8uhDdnYEgIDARo8CicAJQgCEiECe0Ytp2l-4EIP1dd-I3_jf5XcvlVaAUJfGDhry6EN2dgQsIufsAYaCwoJBNEmoCiRAnV2KkYwRAIgXO3bzd5VF8jLZG8r7dcLJ_FnQBYp1BcxrOvovEa40acCIDhQ14eJRoPwJ6GKgqOkXdaFAsoszl-HIRzYcXKeb7D9
  # known as Docker CMD
  # - codex
  # - --bootstrap-node=spr:xxx
  # - --bootstrap-node=spr:yyy
  # - --data-dir=/data
  #
  # Codex configuration using environment variables
  env:
    # Logging
    CODEX_LOG_LEVEL: INFO
    # TRACE;warn:discv5,providers,manager,cache;warn:libp2p,multistream,switch,transport,tcptransport,semaphore,asyncstreamwrapper,lpstream,mplex,mplexchannel,noise,bufferstream,mplexcoder,secure,chronosstream,connection,connmanager,websock,ws-session
    #
    # Metrics
    # CODEX_METRICS: true
    # CODEX_METRICS_ADDRESS: 0.0.0.0
    # CODEX_METRICS_PORT: 8008
    #
    # API
    CODEX_API_BINDADDR: 0.0.0.0
    CODEX_API_PORT: 8080
    #
    # P2P communication
    # Currently, only one node can be set via env variable - https://github.com/codex-storage/nim-codex/issues/525
    # and we can use codex.args to pass multiple bootstrap nodes
    # CODEX_BOOTSTRAP: ""
    CODEX_NAT: "extip:159.196.192.211"
    CODEX_LISTEN_ADDRS: /ip4/0.0.0.0/tcp/8070
    CODEX_DISC_IP: 0.0.0.0
    CODEX_DISC_PORT: 8090
    #
    # Storage
    CODEX_DATA_DIR: /data
    # b, k/kb, m/mb, g/gb, t/tb, p/pb
    CODEX_STORAGE_QUOTA: 10tb
    #
    # Maintenance
    # s, m, h, d, w
    # CODEX_BLOCK_TTL: 1d
    # CODEX_BLOCK_MI: 10m
    # CODEX_BLOCK_MN: 1000
    #
    # Persistence
    CODEX_PERSISTENCE: true
    CODEX_ETH_PROVIDER: https://rpc.testnet.codex.storage
    # CODEX_ETH_ACCOUNT: 0x1234567890123456789012345678901234567890
    # file name `codex-eth-private-key` will be used as a secret name to be mounted to the Pod
    CODEX_ETH_PRIVATE_KEY: /opt/codex-eth-private-key
    CODEX_MARKETPLACE_ADDRESS: 0xDB2908d724a15d05c0B6B8e8441a8b36E67476d3
    # CODEX_CIRCUIT_DIR: /data/circuits
    CODEX_CIRCOM_R1CS: /data/circuits/proof_main.r1cs
    CODEX_CIRCOM_WASM: /data/circuits/proof_main.wasm
    CODEX_CIRCOM_ZKEY: /data/circuits/proof_main.zkey

  extraEnv:
    - name: CODEX_ETH_PROVIDER
      valueFrom:
        secretKeyRef:
          name: codex-eth-provider
          key: CODEX_ETH_PROVIDER
    #- name: CODEX_ETH_ACCOUNT
    #  valueFrom:
    #    secretKeyRef:
    #      name: codex-eth-private-key
    #      key: CODEX_ETH_PRIVATE_KEY-replica_index-pod_index

  # Extra environment variables
  # extraEnv:
    # When multiple StatefulSets are created, we can use replica_index to pass different ConfigMap/Secrets to each replica
    #      Value                                                    Secrets
    # codex_eth_account_replica_index-pod_index --> codex_eth_account_1_1, codex_eth_account_2_1, codex_eth_account_3_1, ...
    #
    # - name: FOO
    #   value: BAR
    #
    # - name: FOO_CONFIG
    #   valueFrom:
    #     configMapKeyRef:
    #       name: configmap-name
    #       key: configmap-key
    #
    # - name: FOO_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-name
    #       key: secret-key
    #
    # - name: CODEX_ETH_ACCOUNT
    #   valueFrom:
    #     secretKeyRef:
    #       name: codex_eth_account
    #       key: codex_eth_account_replica_index-pod_index

  # Marketplace storage for sale configuration
  # We use postStart lifecycle hook to setup Codex node marketplace configuration via API
  # mutually exclusive with the lifecycle configuration bellow
  marketplace:
    totalSize: "9900000000000"
    duration: "604800"
    minPricePerBytePerSecond: "1"
    totalCollateral: "9999999999999999"

# Init container to pass environment variables dynamically to each replica
initEnv:
  image:
    # Image repository
    repository: bitnami/kubectl
    # Image tag
    tag: latest
    # Image pull policy
    pullPolicy: IfNotPresent
  # Enable init Env container - enabled automatically when replica.count > 1 and service.type.nodeport
  enabled: false
  command: ""
  # command: >-
  #     echo test
  # Disable this if we are not using the initcontainer
  envPath: /opt/env

# Pod ports
ports:
  api:
    enabled: true
    name: api
    containerPort: 8080
  metrics:
    enabled: true
    name: metrics
    containerPort: 8008
  transport:
    enabled: true
    name: libp2p
    containerPort: 8070
  discovery:
    enabled: true
    name: dht
    containerPort: 8090

# Service
service:
  # Service type to deploy - nodeport is required when Codex node should be reachable from the Internet
  type:
    - service
    - nodeport
  # Prettify service name
  # single StatefulSet
  # true:  codex-service   codex-nodeport
  # false: codex-1-service codex-1-nodeport
  # multiple StatefulSets
  # true:  codex-1-service   codex-1-nodeport   codex-2-service   codex-2-nodeport
  # false: codex-1-1-service codex-1-1-nodeport codex-2-1-service codex-2-1-nodeport
  prettify: true
  # API port
  api:
    enabled: true
    port: 8080
  # Metrics port
  metrics:
    enabled: true
    port: 8008
  # Transport port
  transport:
    enabled: true
    # 30000-32767
    nodePort: 30510
    nodePortOffset: 10
  # Discovery port
  discovery:
    enabled: true
    # 30000-32767
    nodePort: 30510
    nodePortOffset: 10

# Extra container ports
extraContainerPorts: []
  # - name: foo
  #   containerPort: 1234
  #   protocol: TCP

# Extra ports
extraPorts: []
  # - name: foo
  #   port: 1234
  #   protocol: TCP

# Ingress for Codex API
ingress:
  # Enable ingress
  enabled: true
  # Override chart full name
  fullnameOverride: ""
  # Ingress class
  class: traefik
  prettify: false
  # Ingress annotations
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "codex-ns-auth@kubernetescrd"
    cert-manager.io/cluster-issuer: "acme-prod"
  tls:
    - secretName: codex-riff-cc
      hosts:
        - codex.riff.cc
  hosts:
    - host: codex.riff.cc
      paths:
        # When podName is blank, URL will use deployed Pod name
        # https://codex.riff.cc/pod-name-1
        # https://codex.riff.cc/pod-name-2
        - path: /
          rewritePath: (/|$)(.*)
          pathType: Prefix
        # When podName is set, in URL we will use that value instead of the deployed Pod name
        # When prettify is set to false, Pod URI will contain the StatefulSet Pod index
        # leadingZeros specify the number of digits in the endpoint Pod name - pod-name-1/01/001
        # https://codex.riff.cc/endpoints/node-01-1
        # https://codex.riff.cc/endpoints/node-02-1
        - path: /storage
          rewritePath: (/|$)(.*)
          pathType: Prefix
          podName: node
          prettify: false
          leadingZeros: 2

# Pod resources
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Startup probe
startupProbe: {}

# Liveness probe
livenessProbe:
  httpGet:
    path: /api/codex/v1/debug/info
    port: '{{ .Values.ports.api.name }}'
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 1200

# Readiness probe
readinessProbe:
  httpGet:
    path: /api/codex/v1/debug/info
    port: '{{ .Values.ports.api.name }}'
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 1200

# Persistence
persistence:
  # Enable persistence using Persistent Volume Claims
  enabled: true
  # Name prefix for Persistent Volume Claims
  name: codex-pvc
  # Use an existing PVC to persist data
  existingClaim: "codex-pvc"
  # Access mode of data volume
  accessModes:
    - ReadWriteMany
  # Size of data volume
  size: 1Pi
  # Storage class of data volume
  storageClassName: "moosefs-storage"
  # Annotations for volume claim template
  annotations: {}
  #  foo: bar
  # Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     foo: bar
  retentionPolicy:
    whenDeleted: Retain

# Additional volumes on the output Deployment definition.
volumes:
- name: codex-eth-private-key
  secret:
    secretName: codex-eth-private-key
    optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

initContainers: []
  # - name: datadir-cleanup
  #   image: busybox:latest
  #   command:
  #     - sh
  #     - -c
  #     - |
  #         echo "clean-up datadir"
  #         rm -rf {{ .Values.codex.env.CODEX_DATA_DIR }}/*
  #   volumeMounts:
  #     - name: '{{ .Values.persistence.name }}'
  #       mountPath: '{{ .Values.codex.env.CODEX_DATA_DIR }}'

# Additional
extraContainers: []
# - name: extra
#   image: busybox:latest
#   command: ['sh', '-c', 'echo "hello"']

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

terminationGracePeriodSeconds: 120

podDisruptionBudget: {}
  # maxUnavailable: 1
  # minAvailable: 1
